# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MegaportCli < Formula
  desc "CLI tool for managing Megaport network infrastructure"
  homepage "https://github.com/megaport/megaport-cli"
  version "0.5.9"
  license "MPL-2.0"

  on_macos do
    on_intel do
      url "https://github.com/megaport/megaport-cli/releases/download/v0.5.9/megaport-cli_0.5.9_darwin_amd64.zip"
      sha256 "477f6872e85605cafb49dfe2511f36544e2fddd381e406dce13326570032f0fb"

      def install
        if File.exist?("megaport-cli_v#{version}")
          bin.install "megaport-cli_v#{version}" => "megaport-cli"
        else
          bin.install "megaport-cli"
        end
      end
    end
    on_arm do
      url "https://github.com/megaport/megaport-cli/releases/download/v0.5.9/megaport-cli_0.5.9_darwin_arm64.zip"
      sha256 "bb494b4ccaaa2b950dc7169715979254e2b6c4cda4bea50138b8641bba0c8e01"

      def install
        if File.exist?("megaport-cli_v#{version}")
          bin.install "megaport-cli_v#{version}" => "megaport-cli"
        else
          bin.install "megaport-cli"
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v0.5.9/megaport-cli_0.5.9_linux_amd64.zip"
        sha256 "218913b8918270773333ef669d4ed0f4a6f3c43d6b01ad59315888872b3f08c1"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v0.5.9/megaport-cli_0.5.9_linux_arm.zip"
        sha256 "55627905d88b7fa087769e17094192be9212809064c048a7d78f5959ce8b5641"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v0.5.9/megaport-cli_0.5.9_linux_arm64.zip"
        sha256 "0688f9888aaca5f617af446e85f3d929e0e10bb6f6dd434d767df27fe555def1"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
  end

  test do
    assert_match "Megaport CLI Version", shell_output("#{bin}/megaport-cli version")
  end
end
