# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MegaportCli < Formula
  desc "CLI tool for managing Megaport network infrastructure"
  homepage "https://github.com/megaport/megaport-cli"
  version "0.10.0"
  license "MPL-2.0"

  on_macos do
    on_intel do
      url "https://github.com/megaport/megaport-cli/releases/download/v0.10.0/megaport-cli_0.10.0_darwin_amd64.zip"
      sha256 "42f829229d0d4795d2579388961a1d1e7cbbd33a04f5e69b7a8cd6f7a493022e"

      def install
        if File.exist?("megaport-cli_v#{version}")
          bin.install "megaport-cli_v#{version}" => "megaport-cli"
        else
          bin.install "megaport-cli"
        end
      end
    end
    on_arm do
      url "https://github.com/megaport/megaport-cli/releases/download/v0.10.0/megaport-cli_0.10.0_darwin_arm64.zip"
      sha256 "49a047a93ea680dfd17b3b1ef3371c237110852ab8f565bad878c059ee1904de"

      def install
        if File.exist?("megaport-cli_v#{version}")
          bin.install "megaport-cli_v#{version}" => "megaport-cli"
        else
          bin.install "megaport-cli"
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v0.10.0/megaport-cli_0.10.0_linux_amd64.zip"
        sha256 "bf7946576f5ffd4ee3b3f937058ff201d3f9532f70f925caeb74628938d0d884"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v0.10.0/megaport-cli_0.10.0_linux_arm.zip"
        sha256 "10a42c7eae5539a736eec700a60e46e02a15b2b42a02113e1846c21579dc3779"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v0.10.0/megaport-cli_0.10.0_linux_arm64.zip"
        sha256 "e0efa704a98f378b7811f229df8173f7918dd64e9f13278c26ae2e0a6c328fc6"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
  end

  test do
    assert_match "Megaport CLI Version", shell_output("#{bin}/megaport-cli version")
  end
end
