# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MegaportCli < Formula
  desc "CLI tool for managing Megaport network infrastructure"
  homepage "https://github.com/megaport/megaport-cli"
  version "1.12.1"
  license "MPL-2.0"

  on_macos do
    on_intel do
      url "https://github.com/megaport/megaport-cli/releases/download/v1.12.1/megaport-cli_1.12.1_darwin_amd64.zip"
      sha256 "654f05c05744b2bbc9d15cb97ac60c5f697f684f0139c36c3991c173e2b2395f"

      def install
        if File.exist?("megaport-cli_v#{version}")
          bin.install "megaport-cli_v#{version}" => "megaport-cli"
        else
          bin.install "megaport-cli"
        end
      end
    end
    on_arm do
      url "https://github.com/megaport/megaport-cli/releases/download/v1.12.1/megaport-cli_1.12.1_darwin_arm64.zip"
      sha256 "122a0595f4b9bdd3b45c1d763621ef2ff13d22bb9759463ec3b464402817ba2f"

      def install
        if File.exist?("megaport-cli_v#{version}")
          bin.install "megaport-cli_v#{version}" => "megaport-cli"
        else
          bin.install "megaport-cli"
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v1.12.1/megaport-cli_1.12.1_linux_amd64.zip"
        sha256 "4b5be139e3d06dfabf6ab64a3971a340b47d2b754eaca3873de75f2d391646f8"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v1.12.1/megaport-cli_1.12.1_linux_arm.zip"
        sha256 "9c891abd48a05c7900b4f3884875405f50e317351eafe1802350a055d9300424"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/megaport/megaport-cli/releases/download/v1.12.1/megaport-cli_1.12.1_linux_arm64.zip"
        sha256 "c30471bc6b5b6e06bc023d563723e436f4181922949252a57ac1cc9ec9a19d55"

        def install
          if File.exist?("megaport-cli_v#{version}")
            bin.install "megaport-cli_v#{version}" => "megaport-cli"
          else
            bin.install "megaport-cli"
          end
        end
      end
    end
  end

  test do
    assert_match "Megaport CLI Version", shell_output("#{bin}/megaport-cli version")
  end
end
